version: '3'
services:
  ethereum:
    image: ethereum/client-go
    command: --http --http.addr "0.0.0.0" --http.port 8545
    ports:
      - "8545:8545"
      - "30303:30303"
    restart: unless-stopped
